runtime: custom
env: flex

service: backend

instance_class: F2

# Optional: automatic scaling
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.6