enum AbsenceReason {
  SICKNESS = 'SICKNESS',
  VACATION = 'VACATION',
  PERSONAL = 'PERSONAL',
  TRAINING = 'TRAINING',
  MATERNITY_LEAVE = 'MATERNITY_LEAVE',
  OTHER = 'OTHER',
}

export default AbsenceReason
